# TODO: if we were to go to production, we would need to add a reverse proxy to serve the static files and the app itself.
# This is a simple example of how to do it with Nginx.
version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=same-secret-key
      - DEBUG=0
      - ALLOWED_HOSTS=127.0.0.1,localhost
  
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app
  db:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cluster
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  static_data:
  cassandra_data:
